projects:
  anet:
    schema:
    - http://localhost:8080/graphql:
        headers:
          # Authenticate as arthur:arthur (base64-encoded)
          Authorization: Basic YXJ0aHVyOmFydGh1cg==
    extensions:
      codegen:
        generates:
          ../src/test/resources/anet.graphql:
            plugins:
              - schema-ast
