projects:
  anet:
    schema: 'http://localhost:8080/graphql?user=arthur&pass=arthur'
    extensions:
      codegen:
        generates:
          ../src/test/resources/anet.graphql:
            plugins:
              - schema-ast
