branches:
  - main
name-template: "ANET $NEXT_PATCH_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
categories:
  - title: '🚀 Features'
    label: feature
  - title: '🎨 Enhancements'
    label: enhancement
  - title : '🖌 Improvements'
    label: improvement
  - title: '🐛 Bug Fixes'
    label: bug
  - title: '⬆️ Dependency Updates'
    label: dependencies
  - title: '🔧 Under the hood'
    label: debt
change-template: "* $TITLE (#$NUMBER)"
exclude-labels:
  - devDependencies
  - internal
  - DevOps
  - documentation
template: |
  ## What’s changed in ANET

  $CHANGES
