##############################################################
#### ANET Server Configuration 
####
#### This is the configuration file for the ANET server. 
####
#### For Production use, replace all areas with ${NAME} with 
#### the correct values for your installation.
####
#### For Development use, create a file called `localSettings.gradle`
#### And set each environment variable there 
####  ie: `run.environment('ANET_SMTP_SERVER', 'my-mail-server.example.com`)
#### Do not make any changes to this file unless they apply to all 
#### developers! 
#### 
##############################################################

# Flag to run the server in development mode
# - Will use Basic authentication (rather than Windows Domain Auth)
# - Will reload the GraphQL Graph on every request. 
developmentMode: true

# Flag to tell the server to redirect all HTTP traffic to HTTPS
# You will need to add an HTTP/80 adapter
redirectToHttps: false

# Settings for the SMTP server to send email 
smtp:
  hostname: ${ANET_SMTP_SERVER}
  port: 25
  username: ${ANET_SMTP_USERNAME}
  password: ${ANET_SMTP_PASSWORD}
  startTls: true
  disabled: true
  nbOfHoursForStaleEmails: 72

# The email address that all automated emails should come from. 
# ex: "ANET <anet@example.com>"
emailFromAddr: "Anet Testing <hunter+anet@dds.mil>"

# The URL that should be used for links in emails
# ex:  "http://anet.yourdomain"
# Should not include an ending slash! 
serverUrl: "http://localhost:3000"

# Whether to time Waffle requests
timeWaffleRequests: true

# Configuration for Waffle. This is the system that ANET uses to perform windows authentication
# See https://github.com/Waffle/waffle
waffleConfig:
  principalFormat: fqn
  roleFormat: both
  allowGuestLogin: false
  impersonate: false
  securityFilterProviders: waffle.servlet.spi.BasicSecurityFilterProvider
  #securityFilterProviders: "waffle.servlet.spi.BasicSecurityFilterProvider waffle.servlet.spi.NegotiateSecurityFilterProvider"
  #"waffle.servlet.spi.NegotiateSecurityFilterProvider/protocols": NTLM
  "waffle.servlet.spi.BasicSecurityFilterProvider/realm": ANET

########################################################
### The below is the default Dropwizard Configuration
### See http://www.dropwizard.io/1.0.6/docs/manual/configuration.html#man-configuration
### For all of the possible configuration options. 
#########################################################
# Configuration for the database Server
# See http://www.dropwizard.io/1.0.6/docs/manual/jdbi.html#configuration
database:
  driverClass: ${ANET_DB_DRIVER}
  user: ${ANET_DB_USERNAME}
  password: ${ANET_DB_PASSWORD}
  url: ${ANET_DB_URL}
  properties:
   date_string_format: ${ANET_DB_DATE_STRING_FORMAT}
   date_class: ${ANET_DB_DATE_CLASS}


# Configuration for the web servers HTTP connectors. 
# See http://www.dropwizard.io/1.0.6/docs/manual/core.html#configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
# The AdminConnector is used for administrative functions of Dropwizard and should not be exposed to users. 
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders: 
      - type: file
        currentLogFilename: ./logs/access.log
        archivedLogFilenamePattern: ./logs/access-%d.log.zip
        archivedFileCount: 5
        logFormat: '[%t{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %h %l %u "%r" %s %b "%i{Referer}" "%i{User-Agent}" %D'
      - type: console
        target: stdout
        logFormat: '[%t{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %h %l %u "%r" %s %b "%i{Referer}" "%i{User-Agent}" %D'

# Configuration for the Freemarker templating library
views:
  .ftl:
    number_format: computer

logging:
  level: INFO
  loggers:
    "io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper" : TRACE
    "mil.dds.anet.resources.LoggingResource" :
      level: TRACE
      appenders:
        - type: file
          currentLogFilename: ./logs/clientLog.log
          archivedLogFilenamePattern: ./logs/clientLog-%d.log.zip
          archivedFileCount: 2
          logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
    "org.skife.jdbi.v2.DBI" :
      level: TRACE
      appenders:
        - type: file
#          additive: false
          currentLogFilename: ./logs/dbLog.log
          archivedLogFilenamePattern: ./logs/dbLog-%d.log.zip
          archivedFileCount: 2
          logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
    "org.sqlite.JDBC" : INFO
    "io.dropwizard.assets.AssetsBundle" : TRACE
    "io.dropwizard.assets.*" : TRACE
    "waffle.servlet.NegotiateSecurityFilter" : TRACE
    "mil.dds.anet.auth.AnetAuthenticationFilter" : TRACE
    "mil.dds.anet.threads.AnetEmailWorker" : DEBUG
    "mil.dds.anet.threads.FutureEngagementWorker" : DEBUG
    "mil.dds.anet.resources.TestingResource" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/testingLogger.log
          archivedLogFilenamePattern: ./logs/testingLogger-%d.log.zip
          archivedFileCount: 2
          logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
    "mil.dds.anet.utils.AnetAuditLogger" :
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/auditLogger.log
          archivedLogFilenamePattern: ./logs/auditLogger-%d.log.zip
          archivedFileCount: 2
          logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
  appenders:
    - type: console
      threshold: TRACE
      target: stdout
      logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/anet.log
      archivedLogFilenamePattern: ./logs/anet-%d.log.zip
      archivedFileCount: 2
      logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'

dictionary:
  SUPPORT_EMAIL_ADDR: support@example.com
  fields:
    task:
      shortLabel: Task
      longLabel: Tasks and Milestones
      plannedCompletion:
        label: 'Planned Completion'
        placeholder: 'Fill in the planned completion date'
      projectedCompletion:
        label: Date of Completion
        placeholder: 'Fill in the date of completion'
      customFieldRef1:
        label: 'Parent task'
        placeholder: 'Start typing to search for a higher level task'
      customField:
        label: 'Custom field'
        placeholder: 'Fill in the custom field'
      customFieldEnum1:
        label: 'Project status'
        enum:
          OPEN: Open
          CLOSED: Closed
      customFieldEnum2:
        label: 'Custom field enum 2'
        enum:
          CUSTOMVALUE1: Custom value 1
          CUSTOMVALUE2: Custom value 2
    person:
      ranks:
        - CIV
        - CTR
        - OR-1
        - OR-2
        - OR-3
        - OR-4
        - OR-5
        - OR-6
        - OR-7
        - OR-8
        - OR-9
        - WO-1
        - WO-2
        - WO-3
        - WO-4
        - WO-5
        - OF-1
        - OF-2
        - OF-3
        - OF-4
        - OF-5
        - OF-6
        - OF-7
        - OF-8
        - OF-9
        - OF-10
    advisor:
      person:
        name: NATO Member
        countries:
          - Albania
          - Armenia
          - Australia
          - Austria
          - Azerbaijan
          - Belgium
          - Bosnia-Herzegovina
          - Bulgaria
          - Croatia
          - Czech Republic
          - Denmark
          - Estonia
          - Finland
          - Georgia
          - Germany
          - Greece
          - Hungary
          - Iceland
          - Italy
          - Latvia
          - Lithuania
          - Luxembourg
          - Macedonia
          - Mongolia
          - Montenegro
          - Netherlands
          - New Zealand
          - Norway
          - Poland
          - Portugal
          - Romania
          - Slovakia
          - Slovenia
          - Spain
          - Sweden
          - Turkey
          - Ukraine
          - United Kingdom
          - United States of America
      position:
        name: NATO Billet
      org:
        name: Advisor Organization
        allOrgName: All EFs / AOs
        longName:
          label: Description
          placeholder: e.g. Force Sustainment
        identificationCode:
          label: UIC
          placeholder: the six character code
    principal:
      person:
        name: Afghan Partner
        countries:
          - Afghanistan
      position:
        name: Afghan Tashkil
      org:
        name: Afghan Government Organization
        longName:
          label: Official Organization Name
          placeholder: e.g. Afghan Ministry of Defense
        identificationCode:
          label: UIC
          placeholder: the six character code
    superUser:
      position:
        name: ANET Super User
    administrator:
      position:
        name: ANET Administrator
  pinned_ORGs:
    - Key Leader Engagement
  non_reporting_ORGs:
    - ANET Administrators
  tasking_ORGs:
    - EF 2.2
    - EF 1
  domainNames:
    - cmil.mil
    - mission.ita
    - nato.int
    - dds.mil
    - "*.isaf.nato.int"
  imagery:
    mapOptions:
      crs: EPSG3857
      homeView:
        location: [34.52, 69.16]
        zoomLevel: 10
      leafletOptions:
        attributionControl: false
    baseLayers:
      - name: OSM
        default: true
        type: tile
        url: "https://tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png"
      - name: World Imagery Tiles
        default: false
        type: tile
        url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
        options:
          tms: false
      - name: World WMS
        default: false
        type: wms
        url: "https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv"
        options:
          layers: GEBCO_LATEST
          format: "image/png"
