##############################################################
#### ANET Server Configuration
####
#### This is the configuration file for the ANET server.
####
#### For Production use, replace all areas with ${NAME} with
#### the correct values for your installation.
####
#### For Development use, create a file called `localSettings.gradle`
#### And set each environment variable there
####  ie: `run.environment('ANET_SMTP_SERVER', 'my-mail-server.example.com`)
#### Do not make any changes to this file unless they apply to all
#### developers!
####
##############################################################

# Flag to run the server in development mode
# - Will run the account deactivation worker once on startup
developmentMode: true

# Flag to tell the server to redirect all HTTP traffic to HTTPS
# You will need to add an HTTP/80 adapter
redirectToHttps: false

# Execution time limit for GraphQL requests in milliseconds
# If you comment it out, there is *no* limit!
graphQlRequestTimeoutMs: 15000

assets:
  cacheControlHeader: max-age=259200, public
  mimeTypes:
    ".js.map": application/json
  overrides:
    /imagery: imagery
    /data: data

# Settings for the SMTP server to send email
smtp:
  hostname: ${ANET_SMTP_SERVER}
  port: ${ANET_SMTP_PORT}
  username: ${ANET_SMTP_USERNAME}
  password: ${ANET_SMTP_PASSWORD}
  sslTrust: ${ANET_SMTP_SSLTRUST}
  startTls: ${ANET_SMTP_STARTTLS}
  disabled: ${ANET_SMTP_DISABLE}
  nbOfHoursForStaleEmails: 72

# The email address that all automated emails should come from.
# ex: "ANET <anet@example.com>"
emailFromAddr: "Anet Testing <hunter+anet@example.com>"

# The URL that should be used for links in emails
# ex:  "http://anet.yourdomain"
# Should not include an ending slash!
serverUrl: "http://localhost:3000"

keycloakConfiguration:
  realm: ANET
  auth-server-url: http://localhost:9080
  ssl-required: none
  register-node-at-startup: true
  register-node-period: 600
  resource: ANET-Client
  show-logout-link: true
  enable-basic-auth: true
  credentials:
    secret: 12869b4c-74ac-43f9-b71e-ff74e07babf9

########################################################
### The below is the default Dropwizard Configuration
### See https://www.dropwizard.io/en/latest/manual/configuration.html#man-configuration
### For all of the possible configuration options.
#########################################################
# Configuration for the database Server
# See https://www.dropwizard.io/en/latest/manual/configuration.html#database
database:
  driverClass: ${ANET_DB_DRIVER}
  user: ${ANET_DB_USERNAME}
  password: ${ANET_DB_PASSWORD}
  url: ${ANET_DB_URL}
  properties:
    date_string_format: ${ANET_DB_DATE_STRING_FORMAT}
    date_class: ${ANET_DB_DATE_CLASS}
  # You can tweak the database connection pool settings for your deployment environment:
  initialSize: 10
  minSize: 10
  maxSize: 80
  maxWaitForConnection: 5 seconds


# Configuration for the web servers HTTP connectors.
# See https://www.dropwizard.io/en/latest/manual/configuration.html#connectors
server:
  applicationConnectors:
    - type: http
      port: ${ANET_PORT}
      acceptorThreads: 2
      selectorThreads: 4
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
# The AdminConnector is used for administrative functions of Dropwizard and should not be exposed to users.
  adminConnectors:
    - type: http
      port: ${ANET_ADMIN_PORT}
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/access.log
        archivedLogFilenamePattern: ./logs/access-%d.log.zip
        archivedFileCount: 5
        logFormat: '[%t{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %h %l %u "%r" %s %b "%i{Referer}" "%i{User-Agent}" %D'
      - type: console
        target: stdout
        logFormat: '[%t{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %h %l %u "%r" %s %b "%i{Referer}" "%i{User-Agent}" %D'

# Configuration for the Freemarker templating library
views:
  .ftl:
    number_format: computer

# Set path of dictionary to be loaded
# If you want to place the dictionary file under a subfolder of main application folder,
# please do not forget to update this parameter!
# For example: If you wish to place dictionary file under a folder named as "config" then update anetDictionaryName as :
# anetDictionaryName: "config/anet-dictionary.yml"
anetDictionaryName: ${ANET_DICTIONARY_NAME}

logging:
  level: INFO
  loggers:
    "com.google.inject.internal.ProxyFactory": ERROR
    "io.dropwizard.assets.AssetsBundle": TRACE
    "io.dropwizard.assets.*": TRACE
    "io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper": TRACE
    "mil.dds.anet.resources.LoggingResource":
      level: TRACE
      appenders:
        - type: file
          currentLogFilename: ./logs/clientLog.log
          archivedLogFilenamePattern: ./logs/clientLog-%d.log.zip
          archivedFileCount: 2
          logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
    "mil.dds.anet.utils.AnetDbLogger":
      level: TRACE
      appenders:
        - type: file
#          additive: false
          currentLogFilename: ./logs/dbLog.log
          archivedLogFilenamePattern: ./logs/dbLog-%d.log.zip
          archivedFileCount: 2
          logFormat: '%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}\t%p\t%m%n'
    "mil.dds.anet": DEBUG
    "mil.dds.anet.utils.AnetAuditLogger":
      level: INFO
      appenders:
        - type: file
          currentLogFilename: ./logs/auditLogger.log
          archivedLogFilenamePattern: ./logs/auditLogger-%d.log.zip
          archivedFileCount: 2
          logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
  appenders:
    - type: console
      threshold: TRACE
      target: stdout
      logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/anet.log
      archivedLogFilenamePattern: ./logs/anet-%d.log.zip
      archivedFileCount: 2
      logFormat: '[%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] %p %c: %m%n'
