from sqlalchemy_mixins import ActiveRecordMixin
from src.core.model.autogenerated.autogenerated import Base


class BaseModel(Base, ActiveRecordMixin):
    """ Base model for all ANET objects
        Contains db session and third party mixin lib
    """
    __abstract__ = True