from sqlalchemy_mixins import ActiveRecordMixin
from src.core.model.autogenerated.autogenerated import Base


class BaseModel(Base, ActiveRecordMixin):
    """ Base model for all ANET objects
        Third party mixin library
    """

    __abstract__ = True
