export const RESET_PAGES = "RESET_PAGES"
export const SET_PAGINATION = "SET_PAGINATION"
export const RESET_PAGINATION = "RESET_PAGINATION"
export const SET_USER_ACTIVITIES_STATE = "SET_USER_ACTIVITIES_STATE"
