const names = [
  { name: "Aashna", gender: "m", ethnicGroup: ["Dari", "Pashto"] },
  { name: "Abdal", gender: "m", ethnicGroup: ["Pashto"] },
  {
    name: "Abdul_Baqi",
    gender: "m",
    ethnicGroup: ["Arabic", "Dari", "Muslim"]
  },
  {
    name: "Abdul_Zahir",
    gender: "m",
    ethnicGroup: ["Arabic", "Dari", "Pakistani", "Muslim"]
  },
  { name: "Abul", gender: "m", ethnicGroup: ["Dari"] },
  { name: "Aghala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Amiergol", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Ano", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Apana", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Apriday", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Ara", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Ariana", gender: "f", ethnicGroup: ["Persian", "Dari", "Tajik"] },
  {
    name: "Asghar",
    gender: "m",
    ethnicGroup: ["Urdu", "Punjabi", "Persian", "Pashto"]
  },
  {
    name: "Ashraf",
    gender: "m",
    ethnicGroup: ["Arabic", "Persian", "Urdu", "Pashto"]
  },
  {
    name: "Ashraf",
    gender: "f",
    ethnicGroup: ["Arabic", "Persian", "Urdu", "Pashto"]
  },
  { name: "Atal", gender: "m", ethnicGroup: ["Pashto", "Indian"] },
  { name: "Azizullah", gender: "m", ethnicGroup: ["Pashto", "Urdu"] },
  { name: "Balbala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Barsala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Basoor", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Benazira", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Bibikhal", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Bismillah", gender: "m", ethnicGroup: ["Urdu", "Pashto", "Muslim"] },
  { name: "Boba", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Dewa", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Farkhunda", gender: "f", ethnicGroup: ["Persian", "Dari"] },
  { name: "Fereshta", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Gabina", gender: "f", ethnicGroup: ["Pashto"] },
  {
    name: "Ghazala",
    gender: "f",
    ethnicGroup: ["Pashto", "Punjabi", "Pakistani"]
  },
  {
    name: "Goštāsp",
    gender: "m",
    ethnicGroup: ["Kurdish", "Pashto", "Balochi"]
  },
  {
    name: "Gulalai",
    gender: "f",
    ethnicGroup: ["Pashto", "Dari", "Pakistani"]
  },
  {
    name: "Hamidullah",
    gender: "m",
    ethnicGroup: ["Muslim", "Dari", "Pashto"]
  },
  { name: "Hask", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Heela", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Helai", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Heley", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Hewad", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Hila", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Hosai", gender: "f", ethnicGroup: ["Pashto"] },
  {
    name: "Ishaq",
    gender: "m",
    ethnicGroup: ["Arabic", "Indian", "Urdu", "Pashto"]
  },
  { name: "Ismatullah", gender: "m", ethnicGroup: ["Dari", "Muslim"] },
  { name: "Jagrali", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Jhamir", gender: "m", ethnicGroup: ["Dari"] },
  { name: "Kaki", gender: "m", ethnicGroup: ["Pashto"] },
  {
    name: "Kashmala",
    gender: "f",
    ethnicGroup: ["Pashto", "Urdu", "Pakistani"]
  },
  { name: "Khadafi", gender: "m", ethnicGroup: ["Dari"] },
  { name: "Khudaidad", gender: "m", ethnicGroup: ["Dari"] },
  {
    name: "Khushal",
    gender: "m",
    ethnicGroup: ["Pashto", "Urdu", "Indian", "Marathi", "Hindi"]
  },
  { name: "Khyber", gender: "m", ethnicGroup: ["Dari"] },
  {
    name: "Kubra",
    gender: "f",
    ethnicGroup: ["Arabic", "Dari", "Persian", "Muslim", "Pakistani"]
  },
  { name: "Lalzari", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Laro", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Lawanga", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Letafat", gender: "f", ethnicGroup: ["Persian", "Dari", "Arabic"] },
  {
    name: "Lotfullah",
    gender: "m",
    ethnicGroup: ["Dari", "Indian", "Pakistani"]
  },
  { name: "Malala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Malang", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Malghalara", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Mina", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Miran", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Muska", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Naghma", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Nanguyalai", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Nangyali", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Nasrat", gender: "m", ethnicGroup: ["Dari"] },
  { name: "Nikmarghah", gender: "f", ethnicGroup: ["Dari", "Pashto"] },
  { name: "Nomyali", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Noorzai", gender: "m", ethnicGroup: ["Dari"] },
  {
    name: "Obaidullah",
    gender: "m",
    ethnicGroup: ["Arabic", "Dari", "Pakistani"]
  },
  { name: "Orbala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Orzala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Palay", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Panra", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Parmina", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Patman", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Patson", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Pohyali", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Rohullah", gender: "m", ethnicGroup: ["Arabic", "Dari"] },
  { name: "Romal", gender: "m", ethnicGroup: ["Dari", "Indian"] },
  { name: "Rostum", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Rubbinah", gender: "f", ethnicGroup: ["Dari", "Muslim", "Pashto"] },
  { name: "Sado", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Sak", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Salar", gender: "m", ethnicGroup: ["Pakistani", "Dari", "Arabic"] },
  { name: "Samandar", gender: "m", ethnicGroup: ["Hindi", "Pashto"] },
  { name: "Sanga", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Selai", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Shahlalai", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Shair", gender: "m", ethnicGroup: ["Arabic", "Indian", "Dari"] },
  { name: "Shamsia", gender: "f", ethnicGroup: ["Dari", "Bengali"] },
  { name: "Shaperai", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Shapoor", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Sharbat", gender: "f", ethnicGroup: ["Dari", "Pashto"] },
  { name: "Shastai", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Shazmina", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Shekiba", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Shino", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Shpon", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Sparli", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Spin", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Spin", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Spinzar", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Spinzar", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Storai", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Surab", gender: "m", ethnicGroup: ["Persian", "Dari"] },
  {
    name: "Tahmina",
    gender: "f",
    ethnicGroup: ["Dari", "Persian", "Literature"]
  },
  { name: "Tameem", gender: "m", ethnicGroup: ["Dari"] },
  { name: "Tanima", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Teri", gender: "m", ethnicGroup: ["Pashto"] },
  {
    name: "Tooba",
    gender: "f",
    ethnicGroup: ["Dari", "Urdu", "Pakistani", "Muslim"]
  },
  { name: "Toraki", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Toryal", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Wajia", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Wardak", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Wowreena", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Wowrina", gender: "f", ethnicGroup: ["Pashto", "Dari"] },
  { name: "Zaib", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Zala", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zalmai", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Zalmay", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Zarbaha", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zardana", gender: "f", ethnicGroup: ["Dari"] },
  { name: "Zarghuna", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zarka", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zarsanga", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zartaj", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zlaikha", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zmarai", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "Zulaikha", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "Zulëixa", gender: "f", ethnicGroup: ["Pashto"] }
]
export default names
