const names = [
  { name: "AASHNA", gender: "m", ethnicGroup: ["Dari", "Pashto"] },
  { name: "ABDAL", gender: "m", ethnicGroup: ["Pashto"] },
  {
    name: "ABDUL_BAQI",
    gender: "m",
    ethnicGroup: ["Arabic", "Dari", "Muslim"]
  },
  {
    name: "ABDUL_ZAHIR",
    gender: "m",
    ethnicGroup: ["Arabic", "Dari", "Pakistani", "Muslim"]
  },
  { name: "ABUL", gender: "m", ethnicGroup: ["Dari"] },
  { name: "AGHALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "AMIERGOL", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "ANO", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "APANA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "APRIDAY", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ARA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ARIANA", gender: "f", ethnicGroup: ["Persian", "Dari", "Tajik"] },
  {
    name: "ASGHAR",
    gender: "m",
    ethnicGroup: ["Urdu", "Punjabi", "Persian", "Pashto"]
  },
  {
    name: "ASHRAF",
    gender: "m",
    ethnicGroup: ["Arabic", "Persian", "Urdu", "Pashto"]
  },
  {
    name: "ASHRAF",
    gender: "f",
    ethnicGroup: ["Arabic", "Persian", "Urdu", "Pashto"]
  },
  { name: "ATAL", gender: "m", ethnicGroup: ["Pashto", "Indian"] },
  { name: "AZIZULLAH", gender: "m", ethnicGroup: ["Pashto", "Urdu"] },
  { name: "BALBALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "BARSALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "BASOOR", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "BENAZIRA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "BIBIKHAL", gender: "f", ethnicGroup: ["Dari"] },
  { name: "BISMILLAH", gender: "m", ethnicGroup: ["Urdu", "Pashto", "Muslim"] },
  { name: "BOBA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "DEWA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "FARKHUNDA", gender: "f", ethnicGroup: ["Persian", "Dari"] },
  { name: "FERESHTA", gender: "f", ethnicGroup: ["Dari"] },
  { name: "GABINA", gender: "f", ethnicGroup: ["Pashto"] },
  {
    name: "GHAZALA",
    gender: "f",
    ethnicGroup: ["Pashto", "Punjabi", "Pakistani"]
  },
  {
    name: "GOŠTĀSP",
    gender: "m",
    ethnicGroup: ["Kurdish", "Pashto", "Balochi"]
  },
  {
    name: "GULALAI",
    gender: "f",
    ethnicGroup: ["Pashto", "Dari", "Pakistani"]
  },
  {
    name: "HAMIDULLAH",
    gender: "m",
    ethnicGroup: ["Muslim", "Dari", "Pashto"]
  },
  { name: "HASK", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "HEELA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "HELAI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "HELEY", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "HEWAD", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "HILA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "HOSAI", gender: "f", ethnicGroup: ["Pashto"] },
  {
    name: "ISHAQ",
    gender: "m",
    ethnicGroup: ["Arabic", "Indian", "Urdu", "Pashto"]
  },
  { name: "ISMATULLAH", gender: "m", ethnicGroup: ["Dari", "Muslim"] },
  { name: "JAGRALI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "JHAMIR", gender: "m", ethnicGroup: ["Dari"] },
  { name: "KAKI", gender: "m", ethnicGroup: ["Pashto"] },
  {
    name: "KASHMALA",
    gender: "f",
    ethnicGroup: ["Pashto", "Urdu", "Pakistani"]
  },
  { name: "KHADAFI", gender: "m", ethnicGroup: ["Dari"] },
  { name: "KHUDAIDAD", gender: "m", ethnicGroup: ["Dari"] },
  {
    name: "KHUSHAL",
    gender: "m",
    ethnicGroup: ["Pashto", "Urdu", "Indian", "Marathi", "Hindi"]
  },
  { name: "KHYBER", gender: "m", ethnicGroup: ["Dari"] },
  {
    name: "KUBRA",
    gender: "f",
    ethnicGroup: ["Arabic", "Dari", "Persian", "Muslim", "Pakistani"]
  },
  { name: "LALZARI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "LARO", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "LAWANGA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "LETAFAT", gender: "f", ethnicGroup: ["Persian", "Dari", "Arabic"] },
  {
    name: "LOTFULLAH",
    gender: "m",
    ethnicGroup: ["Dari", "Indian", "Pakistani"]
  },
  { name: "MALALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "MALANG", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "MALGHALARA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "MINA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "MIRAN", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "MUSKA", gender: "f", ethnicGroup: ["Dari"] },
  { name: "NAGHMA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "NANGUYALAI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "NANGYALI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "NASRAT", gender: "m", ethnicGroup: ["Dari"] },
  { name: "NIKMARGHAH", gender: "f", ethnicGroup: ["Dari", "Pashto"] },
  { name: "NOMYALI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "NOORZAI", gender: "m", ethnicGroup: ["Dari"] },
  {
    name: "OBAIDULLAH",
    gender: "m",
    ethnicGroup: ["Arabic", "Dari", "Pakistani"]
  },
  { name: "ORBALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ORZALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "PALAY", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "PANRA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "PARMINA", gender: "f", ethnicGroup: ["Dari"] },
  { name: "PATMAN", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "PATSON", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "POHYALI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "ROHULLAH", gender: "m", ethnicGroup: ["Arabic", "Dari"] },
  { name: "ROMAL", gender: "m", ethnicGroup: ["Dari", "Indian"] },
  { name: "ROSTUM", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "RUBBINAH", gender: "f", ethnicGroup: ["Dari", "Muslim", "Pashto"] },
  { name: "SADO", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SAK", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SALAR", gender: "m", ethnicGroup: ["Pakistani", "Dari", "Arabic"] },
  { name: "SAMANDAR", gender: "m", ethnicGroup: ["Hindi", "Pashto"] },
  { name: "SANGA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SELAI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SHAHLALAI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SHAIR", gender: "m", ethnicGroup: ["Arabic", "Indian", "Dari"] },
  { name: "SHAMSIA", gender: "f", ethnicGroup: ["Dari", "Bengali"] },
  { name: "SHAPERAI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SHAPOOR", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SHARBAT", gender: "f", ethnicGroup: ["Dari", "Pashto"] },
  { name: "SHASTAI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SHAZMINA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SHEKIBA", gender: "f", ethnicGroup: ["Dari"] },
  { name: "SHINO", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SHPON", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SPARLI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SPIN", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SPIN", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SPINZAR", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "SPINZAR", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "STORAI", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "SURAB", gender: "m", ethnicGroup: ["Persian", "Dari"] },
  {
    name: "TAHMINA",
    gender: "f",
    ethnicGroup: ["Dari", "Persian", "Literature"]
  },
  { name: "TAMEEM", gender: "m", ethnicGroup: ["Dari"] },
  { name: "TANIMA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "TERI", gender: "m", ethnicGroup: ["Pashto"] },
  {
    name: "TOOBA",
    gender: "f",
    ethnicGroup: ["Dari", "Urdu", "Pakistani", "Muslim"]
  },
  { name: "TORAKI", gender: "f", ethnicGroup: ["Dari"] },
  { name: "TORYAL", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "WAJIA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "WARDAK", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "WOWREENA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "WOWRINA", gender: "f", ethnicGroup: ["Pashto", "Dari"] },
  { name: "ZAIB", gender: "f", ethnicGroup: ["Dari"] },
  { name: "ZALA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZALMAI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "ZALMAY", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "ZARBAHA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZARDANA", gender: "f", ethnicGroup: ["Dari"] },
  { name: "ZARGHUNA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZARKA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZARSANGA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZARTAJ", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZLAIKHA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZMARAI", gender: "m", ethnicGroup: ["Pashto"] },
  { name: "ZULAIKHA", gender: "f", ethnicGroup: ["Pashto"] },
  { name: "ZULËIXA", gender: "f", ethnicGroup: ["Pashto"] }
]
export default names
