me {
  uuid
  name
  rank
  role
  emailAddress
  status
  pendingVerification
  avatar(size: 32)
  code
  authorizationGroupUuids
  position {
    uuid
    name
    code
    type
    status
    isApprover
    organization {
      uuid
      shortName
      longName
      identificationCode
      descendantOrgs {
        uuid
      }
    }
    location {
      uuid
      name
    }
    associatedPositions {
      uuid
      name
      code
      type
      status
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
      location {
        uuid
        name
      }
      person {
        uuid
        name
        rank
        avatar(size: 32)
        position {
          uuid
          name
          type
          code
          status
          organization {
            uuid
            shortName
            longName
            identificationCode
          }
          location {
            uuid
            name
          }
        }
        customFields
        notes {
          noteRelatedObjects {
            objectUuid
          }
          createdAt
          type
          text
        }
      }
    }
    responsibleTasks(
      query: {
        status: ACTIVE
      }
    ) {
      uuid
      shortName
      longName
      parentTask {
        uuid
        shortName
      }
      ascendantTasks(query: { pageNum: 0, pageSize: 0 }) {
        uuid
        shortName
        parentTask {
          uuid
        }
      }
      customFields
      notes {
        noteRelatedObjects {
          objectUuid
        }
        createdAt
        type
        text
      }
    }
  }
}

adminSettings {
  key
  value
}

topLevelAdvisorOrgs: organizationList(
  query: {
    pageSize: 0
    hasParentOrg: false
    status: ACTIVE
    type: ADVISOR_ORG
  }
) {
  list {
    uuid
    shortName
    longName
    identificationCode
  }
}

topLevelPrincipalOrgs: organizationList(
  query: {
    pageSize: 0
    hasParentOrg: false
    status: ACTIVE
    type: PRINCIPAL_ORG
  }
) {
  list {
    uuid
    shortName
    longName
    identificationCode
  }
}
