me {
  uuid
  name
  rank
  entityAvatar {
    attachmentUuid
    applyCrop
    cropLeft
    cropTop
    cropWidth
    cropHeight
  }
  status
  emailAddresses {
    network
    address
  }
  pendingVerification
  code
  authorizationGroups {
    uuid
  }
  position {
    uuid
    name
    code
    type
    status
    isApprover
    organization {
      uuid
      shortName
      longName
      identificationCode
      descendantOrgs {
        uuid
      }
    }
    location {
      uuid
      name
    }
    associatedPositions {
      uuid
      name
      code
      type
      status
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
      location {
        uuid
        name
      }
      person {
        uuid
        name
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
        position {
          uuid
          name
          type
          code
          status
          organization {
            uuid
            shortName
            longName
            identificationCode
          }
          location {
            uuid
            name
          }
        }
        customFields
        notes {
          noteRelatedObjects {
            objectUuid
          }
          createdAt
          text
        }
      }
    }
    responsibleTasks(
      query: {
        status: ACTIVE
      }
    ) {
      uuid
      shortName
      longName
      parentTask {
        uuid
        shortName
      }
      ascendantTasks(query: { pageNum: 0, pageSize: 0 }) {
        uuid
        shortName
        parentTask {
          uuid
        }
      }
      customFields
      notes {
        noteRelatedObjects {
          objectUuid
        }
        createdAt
        text
      }
    }
  }
}

adminSettings {
  key
  value
}

topLevelOrgs: organizationList(
  query: {
    pageSize: 0
    hasParentOrg: false
    status: ACTIVE
  }
) {
  list {
    uuid
    shortName
    longName
    identificationCode
    app6standardIdentity
  }
}
