authorizationGroupList(query:{pageSize:0}) {
  list {
    uuid
    name
    description
    status
    authorizationGroupRelatedObjects {
      relatedObjectType
      relatedObjectUuid
      relatedObject {
	... on Organization {
	  uuid
	  shortName
	}
	... on Person {
	  uuid
	  name
	  rank
	  avatarUuid
	}
	... on Position {
	  uuid
	  type
	  name
	}
      }
    }
  }
}
