reportList(query: {releasedAtStart: -259200000, pageSize: 3, sortBy: RELEASED_AT, sortOrder: DESC}) {
  pageNum
  totalCount
  list {
    uuid
    intent
    engagementDate
    duration
    keyOutcomes
    nextSteps
    cancelledReason
    atmosphere
    atmosphereDetails
    state
    authors {
      uuid
      name
      rank
      avatarUuid
    }
    primaryAdvisor {
      uuid
      name
      rank
      avatarUuid
    }
    primaryInterlocutor {
      uuid
      name
      rank
      avatarUuid
    }
    advisorOrg {
      uuid
      shortName
      longName
      identificationCode
    }
    interlocutorOrg {
      uuid
      shortName
      longName
      identificationCode
    }
    location {
      uuid
      name
      lat
      lng
    }
    tasks {
      uuid
      shortName
    }
    workflow {
      type
      createdAt
      step {
        uuid
        name
        approvers {
          uuid
          name
          person {
            uuid
            name
            rank
            avatarUuid
          }
        }
      }
      person {
        uuid
        name
        rank
        avatarUuid
      }
    }
    updatedAt
  }
}
