reportList(query: {releasedAtStart: -259200000, pageSize: 3, sortBy: RELEASED_AT, sortOrder: DESC}) {
  pageNum
  totalCount
  list {
    uuid
    intent
    engagementDate
    duration
    keyOutcomes
    nextSteps
    cancelledReason
    atmosphere
    atmosphereDetails
    state
    author {
      uuid
      name
      rank
      role
    }
    primaryAdvisor {
      uuid
      name
      rank
      role
    }
    primaryPrincipal {
      uuid
      name
      rank
      role
    }
    advisorOrg {
      uuid
      shortName
    }
    principalOrg {
      uuid
      shortName
    }
    location {
      uuid
      name
      lat
      lng
    }
    tasks {
      uuid
      shortName
    }
    tags {
      uuid
      name
      description
    }
    workflow {
      type
      createdAt
      step {
        uuid
        name
        approvers {
          uuid
          name
          person {
            uuid
            name
            rank
            role
          }
        }
      }
      person {
        uuid
        name
        rank
        role
      }
    }
    updatedAt
  }
}
