mySubscriptionUpdates(query: {pageSize:0}) {
  pageNum
  pageSize
  totalCount
  list {
    createdAt
    updatedObjectType
    updatedObjectUuid
    updatedObject {
      ... on Location {
        name
      }
      ... on Organization {
        shortName
      }
      ... on Person {
        role
        rank
        name
      }
      ... on Position {
        type
        name
      }
      ... on Report {
        intent
      }
      ... on Task {
        shortName
        longName
      }
    }
    isNote
    subscription {
      uuid
      createdAt
      updatedAt
      subscribedObjectType
      subscribedObjectUuid
      subscribedObject {
        ... on Location {
          name
        }
        ... on Organization {
          shortName
        }
        ... on Person {
          role
          rank
          name
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
}
