organizationList(query: {pageSize: 0}) {
  totalCount
  list {
    uuid
    shortName
    longName
    children: childrenOrgs(query: {pageSize: 0}) {
      uuid
    }
    activeChildren: childrenOrgs(query: {pageSize: 0, status: ACTIVE}) {
      uuid
    }
    inactiveChildren: childrenOrgs(query: {pageSize: 0, status: INACTIVE}) {
      uuid
    }
    activeChildrenCopy: childrenOrgs(query: {pageSize: 0, status: ACTIVE}) {
      uuid
    }
    descendants: descendantOrgs(query: {pageSize: 0}) {
      uuid
    }
    activeDescendants: descendantOrgs(query: {pageSize: 0, status: ACTIVE}) {
      uuid
    }
    inactiveDescendants: descendantOrgs(query: {pageSize: 0, status: INACTIVE}) {
      uuid
    }
    activeDescendants: descendantOrgs(query: {pageSize: 0, status: ACTIVE}) {
      uuid
    }
  }
}
