organization(uuid:"${orgUuid}") {
  uuid
  shortName
  longName
  status
  isSubscribed
  updatedAt
  identificationCode
  type
  parentOrg {
    uuid
    shortName
    longName
    identificationCode
  }
  childrenOrgs {
    uuid
    shortName
    longName
    identificationCode
  }
  positions {
    uuid
    name
    code
    status
    type,
    person {
      uuid
      name
      status
      rank
      role
      avatar(size: 32)
    }
    associatedPositions {
      uuid
      name
      type
      code
      status
      person {
        uuid
        name
        status
        rank
        role
        avatar(size: 32)
      }
    }
  }
  approvalSteps {
    uuid
    name
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        role
        avatar(size: 32)
      }
    }
  }
  notes {
    uuid
    createdAt
    updatedAt
    type
    text
    author {
      uuid
      name
      rank
      role
    }
    noteRelatedObjects {
      noteUuid
      relatedObjectType
      relatedObjectUuid
    }
  }
}
