organization(uuid:"${orgUuid}") {
  uuid
  shortName
  longName
  identificationCode
  status
  isSubscribed
  updatedAt
  type
  parentOrg {
    uuid
    shortName
    longName
    identificationCode
  }
  childrenOrgs {
    uuid
    shortName
    longName
    identificationCode
  }
  positions {
    uuid
    name
    code
    status
    type
    person {
      uuid
      name
      rank
      role
      avatarUuid
      status
    }
    associatedPositions {
      uuid
      name
      type
      code
      status
      person {
        uuid
        name
        rank
        role
        avatarUuid
        status
      }
    }
  }
  planningApprovalSteps {
    uuid
    name
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        role
        avatarUuid
      }
    }
  }
  approvalSteps {
    uuid
    name
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        role
        avatarUuid
      }
    }
  }
  notes {
    uuid
    createdAt
    updatedAt
    type
    assessmentKey
    text
    author {
      uuid
      name
      rank
      role
      avatarUuid
    }
    noteRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          role
          avatarUuid
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
}
