personList(query:{pageSize:0}) {
  list {
    uuid
    name
    rank
    role
    avatarUuid
    emailAddress
    position {
      uuid
      name
      type
      code
      location {
        uuid
        name
      }
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
    }
    customFields
  }
}
