personRecents(maxResults:${maxResults}) {
  list {
    uuid
    name
    rank
    role
    status
    endOfTourDate
    avatar(size: 32)
    position {
      uuid
      name
      type
      status
      organization {
        uuid
        shortName
      }
      location {
        uuid
        name
      }
    }
  }
}
