personList(query:{pageNum:${pageNum}, pageSize:${pageSize}}) {
  list {
    uuid
    name
    rank
    avatarUuid
    emailAddresses {
      network
      address
    }
    position {
      uuid
      name
      type
      code
      location {
        uuid
        name
      }
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
    }
    customFields
  }
}
