personList(query: {status: ACTIVE, inMyReports: true, sortBy: RECENT, sortOrder: DESC}) {
  list {
    uuid
    name
    rank
    entityAvatar {
      attachmentUuid
      applyCrop
      cropLeft
      cropTop
      cropWidth
      cropHeight
    }
    status
    endOfTourDate
    position {
      uuid
      name
      type
      status
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
      location {
        uuid
        name
      }
    }
    customFields
  }
}
