person(uuid:"${personUuid}") {
    uuid,
    name, rank, role, emailAddress, phoneNumber, biography, country, gender, endOfTourDate
    position {
        uuid,
        name,
        organization {
            uuid,
            shortName, longName
        }
    },
    authoredReports(query: {pageSize: 10}) { list {
        uuid,
        engagementDate, duration,
        advisorOrg { uuid, shortName, longName }
        intent,
        author {
            uuid,
            name
        }
    }},
    attendedReports(query: {pageSize: 10}) { list {
        uuid,
        engagementDate, duration,
        advisorOrg { uuid, shortName, longName }
        intent,
        author {
            uuid,
            name
        }
    }}
    previousPositions { startTime, endTime, position { uuid, name } }
    notes { uuid createdAt updatedAt type text author { uuid name rank role } noteRelatedObjects { noteUuid relatedObjectType relatedObjectUuid } }
}
