person(uuid:"${personUuid}") {
  uuid
  name
  rank
  entityAvatar {
    attachmentUuid
    applyCrop
    cropLeft
    cropTop
    cropWidth
    cropHeight
  }
  status
  pendingVerification
  isSubscribed
  updatedAt
  emailAddresses {
    network
    address
  }
  phoneNumber
  user
  users {
    uuid
    domainUsername
  }
  biography
  obsoleteCountry
  country {
    uuid
    name
  }
  gender
  endOfTourDate
  position {
    uuid
    name
    type
    organization {
      uuid
      shortName
      longName
      identificationCode
    }
    associatedPositions {
      uuid
      name
      type
      person {
        uuid
        name
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
      }
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
    }
  }
  previousPositions {
    startTime
    endTime
    position {
      uuid
      name
    }
  }
  assessments {
    uuid
    createdAt
    updatedAt
    assessmentKey
    assessmentValues
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    assessmentRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
  notes {
    uuid
    createdAt
    updatedAt
    text
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    noteRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
  customFields
}
