personList(query:{pageSize:0}) {
  list {
    uuid
    name
    rank
    entityAvatar {
      attachmentUuid
      applyCrop
      cropLeft
      cropTop
      cropWidth
      cropHeight
    }
    emailAddresses {
      network
      address
    }
    position {
      uuid
      name
      type
      code
      location {
        uuid
        name
      }
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
    }
    customFields
  }
}
