person(uuid:"${personUuid}") {
  uuid
  name
  rank
  role
  status
  isSubscribed
  updatedAt
  emailAddress
  phoneNumber
  domainUsername
  biography
  country
  gender
  endOfTourDate
  avatar(size: 256)
  position {
    uuid
    name
    type
    organization {
      uuid
      shortName
    }
    associatedPositions {
      uuid
      name
      type
      person {
        uuid
        name
        rank
        role
        avatar(size: 32)
      }
      organization {
        uuid
        shortName
      }
    }
  }
  previousPositions {
    startTime
    endTime
    position {
      uuid
      name
    }
  }
  notes {
    uuid
    createdAt
    updatedAt
    type
    text
    author {
      uuid
      name
      rank
      role
    }
    noteRelatedObjects {
      noteUuid
      relatedObjectType
      relatedObjectUuid
    }
  }
}
