position(uuid:"${positionUuid}") {
  uuid
  name
  type
  status
  isSubscribed
  updatedAt
  code
  organization {
    uuid
    shortName
    longName
    identificationCode
  }
  person {
    uuid
    name
    rank
    role
    avatar(size: 32)
  }
  associatedPositions {
    uuid
    name
    type
    person {
      uuid
      name
      rank
      role
      avatar(size: 32)
    }
    organization {
      uuid
      shortName
      longName
      identificationCode
    }
  }
  previousPeople {
    startTime
    endTime
    person {
      uuid
      name
      rank
      role
      avatar(size: 32)
    }
  }
  location {
    uuid
    name
  }
  notes {
    uuid
    createdAt
    updatedAt
    type
    assessmentKey
    text
    author {
      uuid
      name
      rank
      role
    }
    noteRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          role
          rank
          name
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
}
