position(uuid:"${positionUuid}") {
  uuid
  name
  type
  status
  isSubscribed
  updatedAt
  code
  organization {
    uuid
    shortName
    longName
    identificationCode
  }
  person {
    uuid
    name
    rank
    entityAvatar {
      attachmentUuid
      applyCrop
      cropLeft
      cropTop
      cropWidth
      cropHeight
    }
  }
  associatedPositions {
    uuid
    name
    type
    person {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    organization {
      uuid
      shortName
      longName
      identificationCode
    }
  }
  previousPeople {
    startTime
    endTime
    person {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
  }
  location {
    uuid
    name
  }
  notes {
    uuid
    createdAt
    updatedAt
    text
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    noteRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
}
