locationList(query: {pageSize: 6, status: ACTIVE, inMyReports: true, sortBy: RECENT, sortOrder: DESC}) {
  list {
    uuid
    name
  }
}
personList(query: {pageSize: 6, status: ACTIVE, inMyReports: true, sortBy: RECENT, sortOrder: DESC}) {
  list {
    uuid
    name
    rank
    role
    status
    endOfTourDate
    avatar(size: 32)
    position {
      uuid
      name
      type
      status
      organization {
        uuid
        shortName
      }
      location {
        uuid
        name
      }
    }
  }
}
taskList(query: {pageSize: 6, status: ACTIVE, inMyReports: true, sortBy: RECENT, sortOrder: DESC}) {
  list {
    uuid
    shortName
    longName
    taskedOrganizations {
      uuid
      shortName
    }
    customFields
  }
}
authorizationGroupList(query: {pageSize: 6, status: ACTIVE, inMyReports: true, sortBy: RECENT, sortOrder: DESC}) {
  list {
    uuid
    name
    description
  }
}
tagList(query: {pageSize: 0}) {
  list {
    uuid
    name
    description
  }
}
