report(uuid:"${reportUuid}") {
  uuid
  intent
  engagementDate
  duration
  atmosphere
  atmosphereDetails
  keyOutcomes
  reportText
  nextSteps
  cancelledReason
  releasedAt
  state
  isSubscribed
  updatedAt
  location {
    uuid
    name
  }
  author {
    uuid
    name
    rank
    role
    avatar(size: 32)
    position {
      uuid
      organization {
        uuid
        shortName
        longName
        identificationCode
        approvalSteps {
          uuid
          name
          approvers {
            uuid
            name
            person {
              uuid
              name
              rank
              role
              avatar(size: 32)
            }
          }
        }
      }
    }
  }
  attendees {
    uuid
    name
    primary
    rank
    role
    status
    endOfTourDate
    avatar(size: 32)
    position {
      uuid
      name
      type
      code
      status
      organization {
        uuid
        shortName
      }
      location {
        uuid
        name
      }
    }
  }
  primaryAdvisor {
    uuid
  }
  primaryPrincipal {
    uuid
  }
  tasks {
    uuid
    shortName
    longName
    responsibleOrg {
      uuid
      shortName
    }
  }
  comments {
    uuid
    text
    createdAt
    updatedAt
    author {
      uuid
      name
      rank
      role
      avatar(size: 32)
    }
  }
  principalOrg {
    uuid
    shortName
    longName
    identificationCode
    type
  }
  advisorOrg {
    uuid
    shortName
    longName
    identificationCode
    type
  }
  workflow {
    type
    createdAt
    step {
      uuid
      name
      approvers {
        uuid
        name
        person {
          uuid
          name
          rank
          role
          avatar(size: 32)
        }
      }
    }
    person {
      uuid
      name
      rank
      role
      avatar(size: 32)
    }
  }
  approvalStep {
    uuid
    name
    approvers {
      uuid
    }
    nextStepUuid
  }
  tags {
    uuid
    name
    description
  }
  reportSensitiveInformation {
    uuid
    text
  }
  authorizationGroups {
    uuid
    name
    description
  }
  notes {
    uuid
    createdAt
    updatedAt
    type
    text
    author {
      uuid
      name
      rank
      role
    }
    noteRelatedObjects {
      noteUuid
      relatedObjectType
      relatedObjectUuid
    }
  }
}
