reportList(query:{pageSize:100}) {
  totalCount
  list {
    uuid
    intent
    engagementDate
    duration
    keyOutcomes
    nextSteps
    cancelledReason
    atmosphere
    atmosphereDetails
    state
    authors {
      uuid
      name
      rank
      role
      avatarUuid
    }
    primaryAdvisor {
      uuid
      name
      rank
      role
      avatarUuid
    }
    primaryPrincipal {
      uuid
      name
      rank
      role
      avatarUuid
    }
    advisorOrg {
      uuid
      shortName
      longName
      identificationCode
    }
    principalOrg {
      uuid
      shortName
      longName
      identificationCode
    }
    location {
      uuid
      name
      lat
      lng
    }
    tasks {
      uuid
      shortName
      customFields
    }
    workflow {
      type
      createdAt
      step {
        uuid
        name
        approvers {
          uuid
          name
          person {
            uuid
            name
            rank
            role
            avatarUuid
          }
        }
      }
      person {
        uuid
        name
        rank
        role
        avatarUuid
      }
    }
    updatedAt
    customFields
  }
}
