report(uuid:"${reportUuid}") {
    uuid, intent, engagementDate, duration, atmosphere, atmosphereDetails
    keyOutcomes, nextSteps, reportText, 

    state

    location { uuid, name }
    author {
        uuid, name
        position {
            organization {
                shortName, longName
                approvalSteps {
                    uuid, name,
                    approvers {
                        uuid, name,
                        person { uuid, name rank }
                    }
                }
            }
        }
    }

    attendees {
        uuid, name, role, primary
        position { uuid, name }
    }
    primaryAdvisor { uuid }
    primaryPrincipal { uuid }

    tasks { uuid, shortName, longName, responsibleOrg { uuid, shortName} }

    comments {
        uuid, text, createdAt, updatedAt
        author { uuid, name, rank }
    }

    principalOrg { uuid, shortName, longName }
    advisorOrg { uuid, shortName, longName }

    workflow {
        type, createdAt
        step { uuid , name
            approvers { uuid, name, person { uuid, name } }
        },
        person { uuid, name, rank}
    }

    approvalStep { name, approvers { uuid } }

    tags { uuid, name, description }

    notes { uuid createdAt updatedAt type text author { uuid name rank role } noteRelatedObjects { noteUuid relatedObjectType relatedObjectUuid } }

}
