reportList(query:{pageSize:100}) {
  totalCount
  list {
    uuid
    intent
    engagementDate
    duration
    keyOutcomes
    nextSteps
    cancelledReason
    atmosphere
    atmosphereDetails
    state
    authors {
      uuid
      familyName
      givenName
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    primaryAdvisor {
      uuid
      familyName
      givenName
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    primaryInterlocutor {
      uuid
      familyName
      givenName
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    advisorOrg {
      uuid
      shortName
      longName
      identificationCode
    }
    interlocutorOrg {
      uuid
      shortName
      longName
      identificationCode
    }
    location {
      uuid
      name
      lat
      lng
    }
    tasks {
      uuid
      shortName
      customFields
    }
    workflow {
      type
      createdAt
      step {
        uuid
        name
        approvers {
          uuid
          name
          person {
            uuid
            familyName
            givenName
            rank
            entityAvatar {
              attachmentUuid
              applyCrop
              cropLeft
              cropTop
              cropWidth
              cropHeight
            }
          }
        }
      }
      person {
        uuid
        familyName
        givenName
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
      }
    }
    updatedAt
    customFields
  }
}
