locationRecents(maxResults: 6) {
  list {
    uuid
    name
  }
}
personRecents(maxResults: 6) {
  list {
    uuid
    name
    rank
    role
    status
    endOfTourDate
    avatar(size: 32)
    position {
      uuid
      name
      type
      status
      organization {
        uuid
        shortName
      }
      location {
        uuid
        name
      }
    }
  }
}
taskRecents(maxResults: 6) {
  list {
    uuid
    shortName
    longName
      taskedOrganizations {
        uuid
        shortName
      }
  }
}
authorizationGroupRecents(maxResults: 6) {
  list {
    uuid
    name
    description
  }
}
tagList(query: {pageSize: 0}) {
  list {
    uuid
    name
    description
  }
}
