report(uuid:"${reportUuid}") {
  uuid
  intent
  engagementDate
  duration
  atmosphere
  atmosphereDetails
  keyOutcomes
  reportText
  nextSteps
  cancelledReason
  releasedAt
  state
  isSubscribed
  updatedAt
  location {
    uuid
    name
  }
  authors {
    uuid
    name
    rank
    entityAvatar {
      attachmentUuid
      applyCrop
      cropLeft
      cropTop
      cropWidth
      cropHeight
    }
    position {
      uuid
      organization {
        uuid
        shortName
        longName
        identificationCode
        approvalSteps {
          uuid
          name
          approvers {
            uuid
            name
            person {
              uuid
              name
              rank
              entityAvatar {
                attachmentUuid
                applyCrop
                cropLeft
                cropTop
                cropWidth
                cropHeight
              }
            }
          }
        }
      }
    }
  }
  attendees {
    uuid
    name
    rank
    entityAvatar {
      attachmentUuid
      applyCrop
      cropLeft
      cropTop
      cropWidth
      cropHeight
    }
    status
    primary
    endOfTourDate
    position {
      uuid
      name
      type
      code
      status
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
      location {
        uuid
        name
      }
    }
  }
  primaryAdvisor {
    uuid
  }
  primaryInterlocutor {
    uuid
  }
  tasks {
    uuid
    shortName
    longName
    taskedOrganizations {
      uuid
      shortName
      longName
      identificationCode
    }
  }
  comments {
    uuid
    text
    createdAt
    updatedAt
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
  }
  interlocutorOrg {
    uuid
    shortName
    longName
    identificationCode
  }
  advisorOrg {
    uuid
    shortName
    longName
    identificationCode
  }
  workflow {
    type
    createdAt
    step {
      uuid
      name
      approvers {
        uuid
        name
        person {
          uuid
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
      }
    }
    person {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
  }
  approvalStep {
    uuid
    name
    approvers {
      uuid
    }
    nextStepUuid
  }
  reportSensitiveInformation {
    uuid
    text
  }
  authorizedMembers {
    relatedObjectType
    relatedObjectUuid
    relatedObject {
      ... on AuthorizationGroup {
        uuid
        name
      }
      ... on Organization {
        uuid
        shortName
        longName
        identificationCode
      }
      ... on Person {
        uuid
        name
        rank
      }
      ... on Position {
        uuid
        type
        name
      }
    }
  }
  assessments {
    uuid
    createdAt
    updatedAt
    assessmentKey
    assessmentValues
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    assessmentRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
  notes {
    uuid
    createdAt
    updatedAt
    text
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    noteRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
  customFields
}
