reportList (query:{text:"${searchQuery}",pageSize:0}) {
  totalCount
  list {
    uuid
    intent
    engagementDate
    duration
    keyOutcomes
    nextSteps
    cancelledReason
    atmosphere
    atmosphereDetails
    state
    author {
      uuid
      name
      rank
      role
    }
    primaryAdvisor {
      uuid
      name
      rank
      role
    }
    primaryPrincipal {
      uuid
      name
      rank
      role
    }
    advisorOrg {
      uuid
      shortName
    }
    principalOrg {
      uuid
      shortName
    }
    location {
      uuid
      name
      lat
      lng
    }
    tasks {
      uuid
      shortName
    }
    tags {
      uuid
      name
      description
    }
    workflow {
      type
      createdAt
      step {
        uuid
        name
        approvers {
          uuid
          name
          person {
            uuid
            name
            rank
            role
          }
        }
      }
      person {
        uuid
        name
        rank
        role
      }
    }
    updatedAt
  }
}

personList (query:{text:"${searchQuery}",pageSize:0}) {
  totalCount
  list {
    uuid, name, rank, role, emailAddress, avatar(size: 32), position { uuid, name, type, code, location { uuid, name }, organization { uuid, shortName} }
  }
}

positionList (query:{text:"${searchQuery}",pageSize:0}) {
  totalCount
  list {
    uuid , name, code, type, status, location { uuid, name }, organization { uuid, shortName}, person { uuid, name, rank, role, avatar(size: 32) }
  }
}

taskList (query:{text:"${searchQuery}",pageSize:0}) {
  totalCount
  list {
    uuid, shortName, longName
  }
}

locationList (query:{text:"${searchQuery}",pageSize:0}) {
  totalCount
  list {
    uuid, name, lat, lng
  }
}

organizationList (query:{text:"${searchQuery}",pageSize:0}) {
  totalCount
  list {
    uuid, shortName, longName, identificationCode, type
  }
}
