reportList (query:{text:"${searchQuery}",pageNum:0,pageSize:0}) {
	list { uuid, intent, engagementDate, keyOutcomes, nextSteps
        primaryAdvisor { uuid, name, position { organization { uuid, shortName, longName}}},
        primaryPrincipal { uuid, name, position { organization { uuid, shortName, longName}}},
        advisorOrg { uuid, shortName, longName},
        principalOrg { uuid, shortName, longName},
        location { uuid, name},
        tasks {uuid, shortName, longName}
	}
}

personList (query:{text:"${searchQuery}",pageNum:0,pageSize:0}) {
	totalCount, list { uuid, name, rank, emailAddress }
}
positionList (query:{text:"${searchQuery}",pageNum:0,pageSize:0}) {
	totalCount, list { uuid, name, type, organization{ uuid, shortName} , person { uuid, name}}
}
taskList (query:{text:"${searchQuery}",pageNum:0,pageSize:0}) {
	totalCount, list { uuid, shortName, longName}
}
locationList (query:{text:"${searchQuery}",pageNum:0,pageSize:0}) {
	totalCount, list { uuid, name, lat, lng}
}
organizationList (query:{text:"${searchQuery}",pageNum:0,pageSize:0}) {
	totalCount, list { uuid, shortName, longName }
}

