reportList (f:search, query:{text:"${searchQuery}"}) {
	list { uuid, intent, engagementDate, keyOutcomes, nextSteps
        primaryAdvisor { uuid, name, position { organization { uuid, shortName, longName}}},
        primaryPrincipal { uuid, name, position { organization { uuid, shortName, longName}}},
        advisorOrg { uuid, shortName, longName},
        principalOrg { uuid, shortName, longName},
        location { uuid, name},
        tasks {uuid, shortName, longName}
	}
}

personList(f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { uuid, name, rank, emailAddress }
}
positionList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { uuid, name, type, organization{ uuid, shortName} , person { uuid, name}}
}
taskList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { uuid, shortName, longName}
}
locationList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { uuid, name, lat, lng}
}
organizationList (f:search, query:{text:"${searchQuery}"}) { 
	totalCount, list { uuid, shortName, longName }
}

