taskList(query: {pageSize: 0}) {
  totalCount
  list {
    uuid
    shortName
    longName
    draftReports: reports(query: {state: [DRAFT]}) {
      totalCount
      list {
        uuid
      }
    }
    pendingReports: reports(query: {state: [PENDING_APPROVAL]}) {
      totalCount
      list {
        uuid
      }
    }
    publishedReports: reports(query: {state: [PUBLISHED]}) {
      totalCount
      list {
        uuid
      }
    }
    rejectedReports: reports(query: {state: [REJECTED]}) {
      totalCount
      list {
        uuid
      }
    }
    cancelledReports: reports(query: {state: [CANCELLED]}) {
      totalCount
      list {
        uuid
      }
    }
    futureReports: reports(query: {state: [FUTURE]}) {
      totalCount
      list {
        uuid
      }
    }
    approvedReports: reports(query: {state: [APPROVED]}) {
      totalCount
      list {
        uuid
      }
    }
  }
}
