task(uuid: "${taskUuid}") {
  uuid
  shortName
  longName
  selectable
  description
  status
  plannedCompletion
  projectedCompletion
  taskedOrganizations {
    uuid
    shortName
    longName
    identificationCode
  }
  parentTask {
    uuid
    shortName
    parentTask {
      uuid
    }
  }
  ascendantTasks(query: { pageNum: 0, pageSize: 0 }) {
    uuid
    shortName
    parentTask {
      uuid
    }
  }
  descendantTasks(query: { pageNum: 0, pageSize: 0 }) {
    uuid
    shortName
    longName
    parentTask {
      uuid
      shortName
    }
    customFields
    assessments {
      uuid
      createdAt
      updatedAt
      assessmentKey
      assessmentValues
      author {
        uuid
        name
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
      }
      assessmentRelatedObjects {
        objectUuid
        relatedObjectType
        relatedObjectUuid
        relatedObject {
          ... on Organization {
            shortName
            longName
            identificationCode
          }
          ... on Person {
            name
            rank
            entityAvatar {
              attachmentUuid
              applyCrop
              cropLeft
              cropTop
              cropWidth
              cropHeight
            }
          }
          ... on Report {
            intent
          }
          ... on Task {
            shortName
            longName
          }
        }
      }
    }
    notes {
      uuid
      createdAt
      updatedAt
      text
      author {
        uuid
        name
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
      }
      noteRelatedObjects {
        objectUuid
        relatedObjectType
        relatedObjectUuid
        relatedObject {
          ... on AuthorizationGroup {
            name
          }
          ... on Location {
            name
          }
          ... on Organization {
            shortName
            longName
            identificationCode
          }
          ... on Person {
            name
            rank
            entityAvatar {
              attachmentUuid
              applyCrop
              cropLeft
              cropTop
              cropWidth
              cropHeight
            }
          }
          ... on Position {
            type
            name
          }
          ... on Report {
            intent
            engagementDate
            state
          }
          ... on Task {
            shortName
            longName
          }
        }
      }
    }
  }
  responsiblePositions {
    uuid
    name
    code
    type
    status
    organization {
      uuid
      shortName
      longName
      identificationCode
    }
    person {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
  }
  planningApprovalSteps {
    uuid
    name
    restrictedApproval
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
      }
    }
  }
  approvalSteps {
    uuid
    name
    restrictedApproval
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        entityAvatar {
          attachmentUuid
          applyCrop
          cropLeft
          cropTop
          cropWidth
          cropHeight
        }
      }
    }
  }
  customFields
  assessments {
    uuid
    createdAt
    updatedAt
    assessmentKey
    assessmentValues
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    assessmentRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Report {
          intent
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
  notes {
    uuid
    createdAt
    updatedAt
    text
    author {
      uuid
      name
      rank
      entityAvatar {
        attachmentUuid
        applyCrop
        cropLeft
        cropTop
        cropWidth
        cropHeight
      }
    }
    noteRelatedObjects {
      objectUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          name
          rank
          entityAvatar {
            attachmentUuid
            applyCrop
            cropLeft
            cropTop
            cropWidth
            cropHeight
          }
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
          engagementDate
          state
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
}
