task(uuid: "${taskUuid}") {
  uuid
  shortName
  longName
  status
  plannedCompletion
  projectedCompletion
  taskedOrganizations {
    uuid
    shortName
    longName
    identificationCode
  }
  parentTask {
    uuid
    shortName
    parentTask {
      uuid
    }
  }
  ascendantTasks(query: { pageNum: 0, pageSize: 0 }) {
    uuid
    shortName
    parentTask {
      uuid
    }
  }
  descendantTasks(query: { pageNum: 0, pageSize: 0 }) {
    uuid
    shortName
    longName
    parentTask {
      uuid
      shortName
    }
    customFields
    notes {
      uuid
      createdAt
      updatedAt
      type
      assessmentKey
      text
      author {
        uuid
        name
        rank
        role
      }
      noteRelatedObjects {
        noteUuid
        relatedObjectType
        relatedObjectUuid
        relatedObject {
          ... on AuthorizationGroup {
            name
          }
          ... on Location {
            name
          }
          ... on Organization {
            shortName
            longName
            identificationCode
          }
          ... on Person {
            role
            rank
            name
            avatar(size: 32)
          }
          ... on Position {
            type
            name
          }
          ... on Report {
            intent
            engagementDate
            state
          }
          ... on Task {
            shortName
            longName
          }
        }
      }
    }
  }
  responsiblePositions {
    uuid
    name
    code
    type
    status
    organization {
      uuid
      shortName
      longName
      identificationCode
    }
    person {
      uuid
      name
      rank
      role
      avatar(size: 32)
    }
  }
  planningApprovalSteps {
    uuid
    name
    restrictedApproval
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        role
        avatar(size: 32)
      }
    }
  }
  approvalSteps {
    uuid
    name
    restrictedApproval
    approvers {
      uuid
      name
      person {
        uuid
        name
        rank
        role
        avatar(size: 32)
      }
    }
  }
  customFields
  notes {
    uuid
    createdAt
    updatedAt
    type
    assessmentKey
    text
    author {
      uuid
      name
      rank
      role
    }
    noteRelatedObjects {
      noteUuid
      relatedObjectType
      relatedObjectUuid
      relatedObject {
        ... on AuthorizationGroup {
          name
        }
        ... on Location {
          name
        }
        ... on Organization {
          shortName
          longName
          identificationCode
        }
        ... on Person {
          role
          rank
          name
          avatar(size: 32)
        }
        ... on Position {
          type
          name
        }
        ... on Report {
          intent
          engagementDate
          state
        }
        ... on Task {
          shortName
          longName
        }
      }
    }
  }
}
