taskList(query: {status: ACTIVE, inMyReports: true, sortBy: RECENT, sortOrder: DESC}) {
  list {
    uuid
    shortName
    longName
    taskedOrganizations {
      uuid
      shortName
    }
    customFields
  }
}
