taskList(query: {pageSize: 0}) {
  totalCount
  list {
    uuid
    shortName
    longName
    responsiblePositions {
      uuid
      name
      code
      type
      status
      organization {
        uuid
        shortName
        longName
        identificationCode
      }
      person {
        uuid
        name
        rank
        avatarUuid
      }
    }
    customFields
  }
}
