#!/bin/sh

# check for commits to protected branches

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "candidate" ]; then
  echo "You can't commit directly to a protected branch"
  exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
