#!/bin/bash

# --------------------------------------------------
# Install Microsoft ODBC Drivers for Mssql Support
# --------------------------------------------------
# Update packages
sudo apt-get update
# Requirements for curl command
sudo apt install -y curl
sudo apt install -y gnupg gnupg2 gnupg1
sudo curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Download appropriate package for the OS version
# Ubuntu 18.04
sudo curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
# optional: for unixODBC development headers
sudo apt-get install -y unixodbc-dev

# --------------------------------------------------
# Install Python Dependencies
# --------------------------------------------------
# Requirements before installing python-ldap
sudo apt-get install -y libsasl2-dev libldap2-dev libssl-dev
# Install pipenv and dependencies
sudo pip install pipenv
sudo pipenv install --system --skip-lock

# --------------------------------------------------
# Update Autogenerated Models with Current Database Schema
# --------------------------------------------------
python /home/jovyan/work/src/core/utils/autogen/autogen_models.py
